sudo: false
language: rust
rust:
  - nightly
  - beta
  - stable

before_script:
  - |
      pip install 'travis-cargo<0.2' --user &&
      export PATH=$HOME/.local/bin:$PATH

script:
  - TRAVIS_CARGO_NIGHTLY_FEATURE=""
  - |
      travis-cargo build &&
      travis-cargo test &&
      travis-cargo bench &&
      travis-cargo --only stable doc

after_success:
  - travis-cargo --only stable doc-upload

env:
  global:
    secure: D3Q41oGB+szFGYlYnjMNF0QSyOn4IMMYg8jDH4yBtzNNhjmUO9LhNCho9SyQHiMa2jMcPvNWQpV57WR44l+ubwLfCBFm3aqq5bwJ8Jvj9459KiG4NIocq1yN5qyBT6TAbfwZ62z+BHoek6VHdN0pJUdcCNJU9ayB0yIKhABSzeVR/isJOjARCll3pGZ53rywKT20tTwjgAEbfzkKJRXEAL5JUqSeMx6ZykIW8U1BwCOKWaS0kMfXfXmDiHJZmXjJcVHpY2wPxZbk7sbJnR0ayDqpgUSSAUTASwc+cDKahamtpZ1s/R7uZDcXiz/2YLROFI7MmXr1d54DA65DhvA1YhH7dgKl0UurKo3pJ8bJY66UYfrmVHE9lB5Qj1EXRNUR75BQYvwSUZqJpuazoUPJuxQ/8Yvk7dMxcpLsK3EgBGa7oYOC9o32ePTDv9lBynmgRiedT2AgXBaM8N8+x3u8Ws+W3XMPgx17gJEC3I4vgUUiVfjkhiKEiJtcWEWvjm9pXDS/DlbD+96rNifkjUlzvWT0zMZWZSJ1SH7/1y1dxEzrpn4HkQplnnsNsInjVDVwWKrVYp0pYTBcZebGhHxZMJN85Fku3Hg6D/arLVpgCzUjRcy3fpaRVj0Uw8YcvA38GYUtSWmZANUyg3+Q9HhvmiXNER2XkccLpPJXfpW2wnQ=
